import {
  DeleteObjectCommand,
  GetObjectCommand,
  HeadObjectCommand,
  PutObjectCommand,
  S3Client,
} from '@aws-sdk/client-s3'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'
import { env } from '../config/env'
import { HttpStatus } from '../config/enums'
import { logger } from '../config/logger'
import { AppError } from '../utils/app-error'

/**
 * Centralized Cloudflare R2 (S3-compatible) object storage.
 *
 * This is the ONLY module in PRPS that talks to the AWS SDK. Controllers and
 * other services go through `document-storage.service.ts`, which adds the
 * PostgreSQL metadata, RBAC and audit layers on top of these raw operations.
 *
 * Design rules:
 *  - The bucket is PRIVATE. Nothing here produces public `r2.dev` URLs.
 *  - Access uses short-lived presigned URLs or server-side GetObject calls.
 *  - Configuration comes from `config/env` (never hardcoded, never exposed to
 *    the frontend). When R2 is not configured, the operations that need it
 *    fail with a clear 503 while the rest of the application keeps working.
 *  - Object keys are validated here as defence in depth: keys are generated
 *    by PRPS from database ids and never taken from user input.
 */

const MAX_KEY_LENGTH = 1024
/** Probe key used by the health check. Never written, only head-checked. */
const HEALTH_PROBE_KEY = 'health/bucket-probe'

export interface PutObjectInput {
  key: string
  body: Buffer | Uint8Array | string
  contentType: string
  /** Small ASCII metadata pairs stored alongside the object. */
  metadata?: Record<string, string>
}

export interface PresignGetOptions {
  /** Seconds until the URL expires. Defaults to R2_PRESIGN_EXPIRES_IN (300). */
  expiresIn?: number
  /** Forces a download with this filename (Content-Disposition). */
  downloadFileName?: string
}

export interface StorageHealth {
  configured: boolean
  reachable: boolean
  bucket: string
  endpointHost: string
  message: string
}

let cachedClient: S3Client | null = null

/** True when every required R2 variable is present. */
export function isR2Configured(): boolean {
  return Boolean(
    env.r2Endpoint && env.r2BucketName && env.r2AccessKeyId && env.r2SecretAccessKey,
  )
}

/** Names (never values) of the variables that are still missing. */
export function missingR2Variables(): string[] {
  const missing: string[] = []
  if (!env.r2Endpoint) missing.push('R2_ENDPOINT')
  if (!env.r2BucketName) missing.push('R2_BUCKET_NAME')
  if (!env.r2AccessKeyId) missing.push('R2_ACCESS_KEY_ID')
  if (!env.r2SecretAccessKey) missing.push('R2_SECRET_ACCESS_KEY')
  return missing
}

export function r2NotConfiguredError(): AppError {
  const missing = missingR2Variables()
  const hint =
    env.r2AccountId && !env.r2Endpoint
      ? ' R2_ACCOUNT_ID is set but R2_ENDPOINT is also required (https://<accountid>.r2.cloudflarestorage.com).'
      : ''
  return new AppError(
    `Object storage (Cloudflare R2) is not configured. Missing: ${missing.join(', ') || 'R2 configuration'}.${hint} ` +
      'Add the R2_* variables to backend/.env (see .env.example).',
    HttpStatus.ServiceUnavailable,
  )
}

function requireConfigured(): void {
  if (!isR2Configured()) throw r2NotConfiguredError()
}

/**
 * Validates an object key before it is used. Keys are generated by PRPS from
 * database ids, so anything unexpected here indicates a bug or tampering.
 */
export function assertSafeObjectKey(key: string): void {
  if (!key || key.length > MAX_KEY_LENGTH) throw unsafeKeyError()
  if (key.startsWith('/') || key.includes('..') || key.includes('\\')) throw unsafeKeyError()
  for (const char of key) {
    const code = char.charCodeAt(0)
    if (code < 0x20 || code === 0x7f) throw unsafeKeyError()
    if (char === ' ' || char === '*' || char === '?' || char === '"') throw unsafeKeyError()
  }
}

function unsafeKeyError(): AppError {
  return new AppError('Invalid document storage key.', HttpStatus.InternalServerError)
}

/** Lazily created, memoized S3 client configured for Cloudflare R2. */
export function getR2Client(): S3Client {
  requireConfigured()
  if (!cachedClient) {
    cachedClient = new S3Client({
      region: 'auto',
      endpoint: env.r2Endpoint,
      credentials: {
        accessKeyId: env.r2AccessKeyId,
        secretAccessKey: env.r2SecretAccessKey,
      },
      forcePathStyle: false,
    })
  }
  return cachedClient
}

/** Drops the memoized client (test seam for configuration swaps). */
export function resetR2Client(): void {
  cachedClient = null
}

function storageFailure(operation: string, key: string, error: unknown): AppError {
  const reason = error instanceof Error ? error.message : String(error)
  // Log the key and reason only — never credentials.
  logger.error({ event: 'r2.storage_failure', operation, key, reason }, `R2 ${operation} failed`)
  if (isR2Configured()) {
    return new AppError(
      `Object storage ${operation} failed. Please try again or contact support.`,
      HttpStatus.ServiceUnavailable,
    )
  }
  return r2NotConfiguredError()
}

function isNotFound(error: unknown): boolean {
  const err = error as { name?: string; $metadata?: { httpStatusCode?: number } }
  return err?.name === 'NotFound' || err?.$metadata?.httpStatusCode === 404
}

/** Uploads an object. Throws a clear AppError when storage is unavailable. */
export async function putR2Object(input: PutObjectInput): Promise<void> {
  assertSafeObjectKey(input.key)
  requireConfigured()
  try {
    await getR2Client().send(
      new PutObjectCommand({
        Bucket: env.r2BucketName,
        Key: input.key,
        Body: input.body,
        ContentType: input.contentType,
        ...(input.metadata ? { Metadata: input.metadata } : {}),
      }),
    )
  } catch (error) {
    if (error instanceof AppError) throw error
    throw storageFailure('upload', input.key, error)
  }
}

/** True when the object exists. Used for integrity and health checks. */
export async function r2ObjectExists(key: string): Promise<boolean> {
  assertSafeObjectKey(key)
  requireConfigured()
  try {
    await getR2Client().send(new HeadObjectCommand({ Bucket: env.r2BucketName, Key: key }))
    return true
  } catch (error) {
    if (isNotFound(error)) return false
    throw storageFailure('existence check', key, error)
  }
}

/** Server-side object download (backend to R2, no browser involvement). */
export async function getR2Object(key: string): Promise<Buffer> {
  assertSafeObjectKey(key)
  requireConfigured()
  try {
    const result = await getR2Client().send(
      new GetObjectCommand({ Bucket: env.r2BucketName, Key: key }),
    )
    const body = result.Body
    if (!body) return Buffer.alloc(0)
    const withArray = body as { transformToByteArray?: () => Promise<Uint8Array> }
    if (typeof withArray.transformToByteArray === 'function') {
      return Buffer.from(await withArray.transformToByteArray())
    }
    const chunks: Uint8Array[] = []
    for await (const chunk of body as AsyncIterable<Uint8Array>) {
      chunks.push(chunk)
    }
    return Buffer.concat(chunks)
  } catch (error) {
    if (isNotFound(error)) {
      throw new AppError('Stored document is no longer available.', HttpStatus.NotFound)
    }
    throw storageFailure('download', key, error)
  }
}

/**
 * Deletes an object. S3 delete is idempotent (missing keys succeed).
 * Callers treat failure as best-effort: the metadata row stays the source of
 * truth and the failure is logged by the caller.
 */
export async function deleteR2Object(key: string): Promise<void> {
  assertSafeObjectKey(key)
  requireConfigured()
  try {
    await getR2Client().send(new DeleteObjectCommand({ Bucket: env.r2BucketName, Key: key }))
  } catch (error) {
    if (error instanceof AppError) throw error
    throw storageFailure('delete', key, error)
  }
}

/**
 * Short-lived presigned GET URL for a private object. Treated as a bearer
 * URL: the browser only receives it after PRPS RBAC has approved the request
 * and it must never be persisted.
 */
export async function getPresignedR2Url(
  key: string,
  options: PresignGetOptions = {},
): Promise<string> {
  assertSafeObjectKey(key)
  requireConfigured()
  try {
    const downloadName = options.downloadFileName?.replace(/["\\]/g, '')
    const command = new GetObjectCommand({
      Bucket: env.r2BucketName,
      Key: key,
      ...(downloadName
        ? { ResponseContentDisposition: `attachment; filename="${downloadName}"` }
        : {}),
    })
    return await getSignedUrl(getR2Client(), command, {
      expiresIn: options.expiresIn ?? env.r2PresignExpiresInSeconds,
    })
  } catch (error) {
    if (error instanceof AppError) throw error
    throw storageFailure('presigned URL', key, error)
  }
}

/**
 * Non-destructive health probe: a HeadObject against a key that is never
 * written. A 404 means credentials and bucket are reachable (403 or a
 * transport error would not).
 */
export async function checkR2Health(): Promise<StorageHealth> {
  const base = {
    configured: isR2Configured(),
    bucket: env.r2BucketName || '(not set)',
    endpointHost: safeHost(env.r2Endpoint),
  }
  if (!base.configured) {
    return {
      ...base,
      reachable: false,
      message: `Not configured. Missing: ${missingR2Variables().join(', ')}.`,
    }
  }
  try {
    const exists = await r2ObjectExists(HEALTH_PROBE_KEY)
    return {
      ...base,
      reachable: true,
      message: exists
        ? 'Reachable (probe object present).'
        : 'Reachable (probe object absent — expected for a new bucket).',
    }
  } catch (error) {
    return {
      ...base,
      reachable: false,
      message: error instanceof Error ? error.message : 'Storage unreachable.',
    }
  }
}

function safeHost(endpoint: string): string {
  if (!endpoint) return '(not set)'
  try {
    return new URL(endpoint).host
  } catch {
    return '(invalid endpoint)'
  }
}
